ebook_metadata:
  title: ༄༅། །ལེགས་བཤད་བདུད་རྩིའི་ཆུ་རྒྱུན་ཞེས་བྱ་བ་བཞུགས་སོ།
  authors:
  - མཛད་པ་པོ། ཞབས་དཀར་ཚོགས་དྲུག་རང་གྲོལ།
  sku: SHE-SHAP-16
  layers:
  - book_title
  - author
  - quotation
  - yigchung
web_metadata:
  title:
    en: The Stream of Ambrosia:An Excellent Discourse
    bo: ལེགས་བཤད་བདུད་རྩིའི་ཆུ་རྒྱུན་ཞེས་བྱ་བ་བཞུགས་སོ།
  collection:
    en: Shabkar Series–  Book 16
    bo: ཞབས་དཀར་གསུང་འབུམ།–  དེབ། ༡༦
  author:
    en: Shabkar Tsokdruk Rangdrol
    bo: ཞབས་དཀར་ཚོགས་དྲུག་རང་གྲོལ།
  pusblisher:
    en: Shechen Publications
    bo: ཞེ་ཆེན་བསྟན་གཉིས་དར་རྒྱས་གླིང།
  sku: SHE-SHAP-16
  category:
    en: Dharma Teaching
    bo: ཆོས་བསླབ་བྱ།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: SHE-SHAP-16.epub
  description:
    en: ''
    bo: ''
